# Generated by Django 5.2.4 on 2025-08-06 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('RFID', 'RFID Reader'), ('FPRINT', 'Fingerprint Scanner'), ('QR', 'QR Station'), ('OTHER', 'Other')], max_length=10)),
                ('label', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(choices=[('RFID', 'RFID'), ('FPRINT', 'Fingerprint'), ('QR', 'QR'), ('MANUAL', 'Manual')], max_length=10)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=8)),
                ('manual_note', models.CharField(blank=True, max_length=255)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.student')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.device')),
            ],
            options={
                'ordering': ['session', 'student'],
                'indexes': [models.Index(fields=['session', 'student'], name='attendance__session_33d78b_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx'), models.Index(fields=['verification_method'], name='attendance__verific_d19f7a_idx')],
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='courses.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='users.student')),
            ],
            options={
                'ordering': ['session', 'student'],
                'indexes': [models.Index(fields=['session', 'student'], name='attendance__session_60144e_idx')],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
