# Generated by Django 5.2.4 on 2025-08-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='device',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('RFID', 'RFID'), ('QR', 'QR')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
